export type PropertyCategory = "Residential" | "Commercial" | "Plot" | "Agricultural Land";
export type FurnishingStatus = "Furnished" | "Semi Furnished" | "Unfurnished";
export type ConstructionStatus = "Ready To Move" | "Under Construction";

export interface ListingProperty {
  id: number;
  title: string;
  location: string;
  city: string;
  price: number;
  priceLabel: string;
  type: "Sale" | "Rent";
  category: PropertyCategory;
  bedrooms: number;
  bathrooms: number;
  area: string;
  areaSqFt: number;
  image: string;
  createdAt: string;
  furnishing: FurnishingStatus;
  constructionStatus: ConstructionStatus;
  amenities: {
    parking: boolean;
    garden: boolean;
    lift: boolean;
    gym: boolean;
    swimmingPool: boolean;
  };
}

export const cities = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Miami",
  "San Francisco",
  "Austin",
  "Seattle",
  "Denver",
  "Boston",
  "Dallas",
];

export const propertyCategories: PropertyCategory[] = [
  "Residential",
  "Commercial",
  "Plot",
  "Agricultural Land",
];

export const bedroomOptions = [1, 2, 3, 4, 5, 6];

export const allListingProperties: ListingProperty[] = [
  // ──────────── Residential ────────────
  {
    id: 1,
    title: "Modern Luxury Villa",
    location: "Beverly Hills, Los Angeles",
    city: "Los Angeles",
    price: 2450000,
    priceLabel: "$2,450,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 5,
    bathrooms: 4,
    area: "4,200 sq ft",
    areaSqFt: 4200,
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    createdAt: "2026-07-15",
    furnishing: "Semi Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: false, lift: false, gym: true, swimmingPool: true },
  },
  {
    id: 2,
    title: "Downtown Penthouse Suite",
    location: "Manhattan, New York",
    city: "New York",
    price: 8500,
    priceLabel: "$8,500/mo",
    type: "Rent",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 2,
    area: "2,100 sq ft",
    areaSqFt: 2100,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    createdAt: "2026-07-14",
    furnishing: "Unfurnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: false, garden: false, lift: true, gym: true, swimmingPool: false },
  },
  {
    id: 3,
    title: "Seaside Contemporary Home",
    location: "Malibu, Los Angeles",
    city: "Los Angeles",
    price: 3800000,
    priceLabel: "$3,800,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 4,
    bathrooms: 3,
    area: "3,500 sq ft",
    areaSqFt: 3500,
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    createdAt: "2026-07-13",
    furnishing: "Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: true, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 4,
    title: "Cozy Urban Studio Loft",
    location: "SoMa, San Francisco",
    city: "San Francisco",
    price: 3200,
    priceLabel: "$3,200/mo",
    type: "Rent",
    category: "Residential",
    bedrooms: 1,
    bathrooms: 1,
    area: "850 sq ft",
    areaSqFt: 850,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    createdAt: "2026-07-12",
    furnishing: "Semi Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: false, lift: true, gym: false, swimmingPool: false },
  },
  {
    id: 5,
    title: "Mountain View Estate",
    location: "Highlands, Denver",
    city: "Denver",
    price: 5200000,
    priceLabel: "$5,200,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 6,
    bathrooms: 5,
    area: "6,800 sq ft",
    areaSqFt: 6800,
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    createdAt: "2026-07-11",
    furnishing: "Unfurnished",
    constructionStatus: "Under Construction",
    amenities: { parking: false, garden: false, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 6,
    title: "Elegant City Apartment",
    location: "Lincoln Park, Chicago",
    city: "Chicago",
    price: 4800,
    priceLabel: "$4,800/mo",
    type: "Rent",
    category: "Residential",
    bedrooms: 2,
    bathrooms: 2,
    area: "1,400 sq ft",
    areaSqFt: 1400,
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80",
    createdAt: "2026-07-10",
    furnishing: "Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: true, lift: true, gym: true, swimmingPool: true },
  },
  {
    id: 7,
    title: "Waterfront Mansion",
    location: "South Beach, Miami",
    city: "Miami",
    price: 7900000,
    priceLabel: "$7,900,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 6,
    bathrooms: 5,
    area: "8,500 sq ft",
    areaSqFt: 8500,
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
    createdAt: "2026-07-09",
    furnishing: "Semi Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: false, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 8,
    title: "Cozy Suburban Home",
    location: "East Austin, Austin",
    city: "Austin",
    price: 650000,
    priceLabel: "$650,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 2,
    area: "2,200 sq ft",
    areaSqFt: 2200,
    image: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80",
    createdAt: "2026-07-08",
    furnishing: "Unfurnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: false, garden: false, lift: true, gym: false, swimmingPool: false },
  },
  {
    id: 9,
    title: "Luxury Condo Tower",
    location: "Capitol Hill, Seattle",
    city: "Seattle",
    price: 5500,
    priceLabel: "$5,500/mo",
    type: "Rent",
    category: "Residential",
    bedrooms: 2,
    bathrooms: 2,
    area: "1,600 sq ft",
    areaSqFt: 1600,
    image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
    createdAt: "2026-07-07",
    furnishing: "Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: true, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 10,
    title: "Charming Brownstone",
    location: "Back Bay, Boston",
    city: "Boston",
    price: 1850000,
    priceLabel: "$1,850,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 4,
    bathrooms: 3,
    area: "3,100 sq ft",
    areaSqFt: 3100,
    image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80",
    createdAt: "2026-07-06",
    furnishing: "Semi Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: false, lift: true, gym: true, swimmingPool: false },
  },
  {
    id: 11,
    title: "Modern Townhouse",
    location: "Uptown, Dallas",
    city: "Dallas",
    price: 720000,
    priceLabel: "$720,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    area: "2,500 sq ft",
    areaSqFt: 2500,
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    createdAt: "2026-07-05",
    furnishing: "Unfurnished",
    constructionStatus: "Under Construction",
    amenities: { parking: false, garden: false, lift: false, gym: true, swimmingPool: true },
  },
  {
    id: 12,
    title: "Lakefront Family Home",
    location: "Lake View, Chicago",
    city: "Chicago",
    price: 1250000,
    priceLabel: "$1,250,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 5,
    bathrooms: 4,
    area: "4,000 sq ft",
    areaSqFt: 4000,
    image: "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80",
    createdAt: "2026-07-04",
    furnishing: "Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: true, lift: true, gym: false, swimmingPool: false },
  },

  // ──────────── Commercial ────────────
  {
    id: 13,
    title: "Prime Office Space",
    location: "Financial District, New York",
    city: "New York",
    price: 15000,
    priceLabel: "$15,000/mo",
    type: "Rent",
    category: "Commercial",
    bedrooms: 0,
    bathrooms: 4,
    area: "5,200 sq ft",
    areaSqFt: 5200,
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
    createdAt: "2026-07-15",
    furnishing: "Semi Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: false, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 14,
    title: "Retail Storefront Downtown",
    location: "Magnificent Mile, Chicago",
    city: "Chicago",
    price: 2800000,
    priceLabel: "$2,800,000",
    type: "Sale",
    category: "Commercial",
    bedrooms: 0,
    bathrooms: 2,
    area: "3,800 sq ft",
    areaSqFt: 3800,
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80",
    createdAt: "2026-07-14",
    furnishing: "Unfurnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: false, garden: false, lift: true, gym: true, swimmingPool: false },
  },
  {
    id: 15,
    title: "Co-Working Hub",
    location: "DTLA, Los Angeles",
    city: "Los Angeles",
    price: 9500,
    priceLabel: "$9,500/mo",
    type: "Rent",
    category: "Commercial",
    bedrooms: 0,
    bathrooms: 3,
    area: "4,000 sq ft",
    areaSqFt: 4000,
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80",
    createdAt: "2026-07-13",
    furnishing: "Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: true, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 16,
    title: "Tech Startup Office",
    location: "SoDo, Seattle",
    city: "Seattle",
    price: 7200,
    priceLabel: "$7,200/mo",
    type: "Rent",
    category: "Commercial",
    bedrooms: 0,
    bathrooms: 2,
    area: "2,800 sq ft",
    areaSqFt: 2800,
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80",
    createdAt: "2026-07-12",
    furnishing: "Semi Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: false, lift: true, gym: false, swimmingPool: true },
  },
  {
    id: 17,
    title: "Restaurant Space with Patio",
    location: "Wynwood, Miami",
    city: "Miami",
    price: 1950000,
    priceLabel: "$1,950,000",
    type: "Sale",
    category: "Commercial",
    bedrooms: 0,
    bathrooms: 4,
    area: "3,200 sq ft",
    areaSqFt: 3200,
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    createdAt: "2026-07-11",
    furnishing: "Unfurnished",
    constructionStatus: "Under Construction",
    amenities: { parking: false, garden: false, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 18,
    title: "Medical Office Building",
    location: "Brookline, Boston",
    city: "Boston",
    price: 3500000,
    priceLabel: "$3,500,000",
    type: "Sale",
    category: "Commercial",
    bedrooms: 0,
    bathrooms: 6,
    area: "6,500 sq ft",
    areaSqFt: 6500,
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    createdAt: "2026-07-10",
    furnishing: "Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: true, lift: true, gym: true, swimmingPool: false },
  },

  // ──────────── Plot ────────────
  {
    id: 19,
    title: "Premium Residential Plot",
    location: "Westlake, Austin",
    city: "Austin",
    price: 450000,
    priceLabel: "$450,000",
    type: "Sale",
    category: "Plot",
    bedrooms: 0,
    bathrooms: 0,
    area: "8,000 sq ft",
    areaSqFt: 8000,
    image: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    createdAt: "2026-07-15",
    furnishing: "Semi Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: false, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 20,
    title: "Hillside Building Lot",
    location: "Cherry Creek, Denver",
    city: "Denver",
    price: 380000,
    priceLabel: "$380,000",
    type: "Sale",
    category: "Plot",
    bedrooms: 0,
    bathrooms: 0,
    area: "12,000 sq ft",
    areaSqFt: 12000,
    image: "https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&q=80",
    createdAt: "2026-07-14",
    furnishing: "Unfurnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: false, garden: false, lift: true, gym: false, swimmingPool: false },
  },
  {
    id: 21,
    title: "Waterfront Development Lot",
    location: "Key Biscayne, Miami",
    city: "Miami",
    price: 1200000,
    priceLabel: "$1,200,000",
    type: "Sale",
    category: "Plot",
    bedrooms: 0,
    bathrooms: 0,
    area: "15,000 sq ft",
    areaSqFt: 15000,
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80",
    createdAt: "2026-07-13",
    furnishing: "Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: true, lift: false, gym: true, swimmingPool: true },
  },
  {
    id: 22,
    title: "Corner Plot Near Highway",
    location: "Plano, Dallas",
    city: "Dallas",
    price: 290000,
    priceLabel: "$290,000",
    type: "Sale",
    category: "Plot",
    bedrooms: 0,
    bathrooms: 0,
    area: "6,500 sq ft",
    areaSqFt: 6500,
    image: "https://images.unsplash.com/photo-1416339306562-f3d12fefd36f?w=800&q=80",
    createdAt: "2026-07-12",
    furnishing: "Semi Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: false, lift: true, gym: true, swimmingPool: false },
  },
  {
    id: 23,
    title: "Gated Community Plot",
    location: "Pacific Palisades, Los Angeles",
    city: "Los Angeles",
    price: 950000,
    priceLabel: "$950,000",
    type: "Sale",
    category: "Plot",
    bedrooms: 0,
    bathrooms: 0,
    area: "10,500 sq ft",
    areaSqFt: 10500,
    image: "https://images.unsplash.com/photo-1518173946687-a9fcbfe6f9c1?w=800&q=80",
    createdAt: "2026-07-11",
    furnishing: "Unfurnished",
    constructionStatus: "Under Construction",
    amenities: { parking: false, garden: false, lift: false, gym: true, swimmingPool: false },
  },

  // ──────────── Agricultural Land ────────────
  {
    id: 24,
    title: "Fertile Farmland Estate",
    location: "Hill Country, Austin",
    city: "Austin",
    price: 1800000,
    priceLabel: "$1,800,000",
    type: "Sale",
    category: "Agricultural Land",
    bedrooms: 0,
    bathrooms: 0,
    area: "50 acres",
    areaSqFt: 2178000,
    image: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=800&q=80",
    createdAt: "2026-07-15",
    furnishing: "Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: true, lift: true, gym: false, swimmingPool: false },
  },
  {
    id: 25,
    title: "Vineyard Ready Land",
    location: "Sonoma Valley, San Francisco",
    city: "San Francisco",
    price: 3200000,
    priceLabel: "$3,200,000",
    type: "Sale",
    category: "Agricultural Land",
    bedrooms: 0,
    bathrooms: 0,
    area: "75 acres",
    areaSqFt: 3267000,
    image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80",
    createdAt: "2026-07-14",
    furnishing: "Semi Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: false, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 26,
    title: "Ranch Land with Creek",
    location: "Parker County, Dallas",
    city: "Dallas",
    price: 890000,
    priceLabel: "$890,000",
    type: "Sale",
    category: "Agricultural Land",
    bedrooms: 0,
    bathrooms: 0,
    area: "30 acres",
    areaSqFt: 1306800,
    image: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&q=80",
    createdAt: "2026-07-13",
    furnishing: "Unfurnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: false, garden: false, lift: true, gym: true, swimmingPool: true },
  },
  {
    id: 27,
    title: "Organic Farm Property",
    location: "Boulder County, Denver",
    city: "Denver",
    price: 2100000,
    priceLabel: "$2,100,000",
    type: "Sale",
    category: "Agricultural Land",
    bedrooms: 0,
    bathrooms: 0,
    area: "60 acres",
    areaSqFt: 2613600,
    image: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=800&q=80",
    createdAt: "2026-07-12",
    furnishing: "Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: true, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 28,
    title: "Timber & Grazing Land",
    location: "Everett, Seattle",
    city: "Seattle",
    price: 750000,
    priceLabel: "$750,000",
    type: "Sale",
    category: "Agricultural Land",
    bedrooms: 0,
    bathrooms: 0,
    area: "40 acres",
    areaSqFt: 1742400,
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    createdAt: "2026-07-11",
    furnishing: "Semi Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: false, lift: true, gym: false, swimmingPool: false },
  },

  // ──────────── More Residential for pagination ────────────
  {
    id: 29,
    title: "Skyline View Apartment",
    location: "Midtown, New York",
    city: "New York",
    price: 6500,
    priceLabel: "$6,500/mo",
    type: "Rent",
    category: "Residential",
    bedrooms: 2,
    bathrooms: 2,
    area: "1,200 sq ft",
    areaSqFt: 1200,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    createdAt: "2026-07-03",
    furnishing: "Unfurnished",
    constructionStatus: "Under Construction",
    amenities: { parking: false, garden: false, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 30,
    title: "Garden District Mansion",
    location: "Coral Gables, Miami",
    city: "Miami",
    price: 4500000,
    priceLabel: "$4,500,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 5,
    bathrooms: 4,
    area: "5,800 sq ft",
    areaSqFt: 5800,
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
    createdAt: "2026-07-02",
    furnishing: "Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: true, lift: true, gym: true, swimmingPool: false },
  },
  {
    id: 31,
    title: "Industrial Loft Conversion",
    location: "Wicker Park, Chicago",
    city: "Chicago",
    price: 3800,
    priceLabel: "$3,800/mo",
    type: "Rent",
    category: "Residential",
    bedrooms: 1,
    bathrooms: 1,
    area: "1,100 sq ft",
    areaSqFt: 1100,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    createdAt: "2026-07-01",
    furnishing: "Semi Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: false, lift: false, gym: true, swimmingPool: true },
  },
  {
    id: 32,
    title: "Minimalist Smart Home",
    location: "East Side, Austin",
    city: "Austin",
    price: 875000,
    priceLabel: "$875,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 2,
    area: "2,400 sq ft",
    areaSqFt: 2400,
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80",
    createdAt: "2026-06-30",
    furnishing: "Unfurnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: false, garden: false, lift: true, gym: false, swimmingPool: false },
  },
  {
    id: 33,
    title: "Victorian Heritage Home",
    location: "Beacon Hill, Boston",
    city: "Boston",
    price: 2200000,
    priceLabel: "$2,200,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 4,
    bathrooms: 3,
    area: "3,600 sq ft",
    areaSqFt: 3600,
    image: "https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&q=80",
    createdAt: "2026-06-29",
    furnishing: "Furnished",
    constructionStatus: "Under Construction",
    amenities: { parking: true, garden: true, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 34,
    title: "Modern Glass House",
    location: "Venice Beach, Los Angeles",
    city: "Los Angeles",
    price: 6200000,
    priceLabel: "$6,200,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 4,
    bathrooms: 4,
    area: "4,500 sq ft",
    areaSqFt: 4500,
    image: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80",
    createdAt: "2026-06-28",
    furnishing: "Semi Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: false, lift: true, gym: true, swimmingPool: false },
  },
  {
    id: 35,
    title: "Luxury Penthouse Loft",
    location: "River North, Chicago",
    city: "Chicago",
    price: 12000,
    priceLabel: "$12,000/mo",
    type: "Rent",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    area: "2,800 sq ft",
    areaSqFt: 2800,
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    createdAt: "2026-06-27",
    furnishing: "Unfurnished",
    constructionStatus: "Under Construction",
    amenities: { parking: false, garden: false, lift: false, gym: true, swimmingPool: false },
  },
  {
    id: 36,
    title: "Craftsman Bungalow",
    location: "Fremont, Seattle",
    city: "Seattle",
    price: 985000,
    priceLabel: "$985,000",
    type: "Sale",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 2,
    area: "1,900 sq ft",
    areaSqFt: 1900,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    createdAt: "2026-06-26",
    furnishing: "Furnished",
    constructionStatus: "Ready To Move",
    amenities: { parking: true, garden: true, lift: true, gym: false, swimmingPool: true },
  },
];
